dataset:
  observation_fieldnames:
     - index
     - sentence
     - lemma_sentence
     - upos_sentence
     - xpos_sentence
     - morph
     - head_indices
     - governance_relations
     - secondary_relations
     - extra_info
     - embeddings
  corpus:
    root: /home/john/python/rnn-order-data-results/data/ptb-wsj-sd/
    train_path: train-sample.conllx
    dev_path: dev-sample.conllx
    test_path: dev-sample.conllx
  embeddings:
    type: subword #{token,subword}
    root: /home/john/python/rnn-order-data-results/data/ptb-wsj-sd/
    train_path: raw.train.bertbase-layers.hdf5
    dev_path: raw.dev.bertbase-layers.hdf5
    test_path: raw.dev.bertbase-layers.hdf5
  batch_size: 1
  dataset_size: 1000
model:
  hidden_dim: 768 # ELMo hidden dim
  #embedding_dim: 1024 # ELMo word embedding dim
  model_type: BERT-disk # BERT-disk, ELMo-disk, 
  use_disk: True
  model_layer: 11 # BERT-base: {1,...,12}; ELMo: {1,2,3}
probe:
  task_signature: word_pair # word, word_pair
  task_name: balanced-distance
  maximum_rank: 768
  psd_parameters: False
  diagonal: False
  params_path: predictor.params
  probe_spec:
    probe_hidden_layers: 2
probe_training:
  epochs: 40
  loss: L1
reporting:
  root: example/results
  observation_paths:
    train_path: train.observations
    dev_path: dev.observations
    test_path: test.observations
  prediction_paths:
    train_path: train.predictions
    dev_path: dev.predictions
    test_path: test.predictions
  reporting_methods:
    - spearmanr
    - uuas
    - write_predictions
    - placeholder
